<?php
/**
 * Created by PhpStorm.
 * User: leijie
 * Date: 2018/9/12
 * Time: 9:48
 */

namespace app\admin\controller;

use think\Controller;
use app\admin\server\IndexServer;
use think\Db;
use think\facade\Config;

class Index extends Controller
{
    protected $server;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->server = new IndexServer();
        $tp_config = $this->server->getConfig();
        $this->assign('tpshop_config',$tp_config);
    }

    public function index()
    {
        $admin_info = $this->server->getAdminInfo();
        $order_amount = $this->server->getOrderCount();
        $menu = $this->server->getMenuArr();
        $this->assign('order_amount',$order_amount);
        $this->assign('admin_info',$admin_info);
        $this->assign('menu',$menu);
        return $this->fetch();
    }

    public function welcome(){
        $this->assign('sys_info',$this->get_sys_info());
//    	$today = strtotime("-1 day");
        $today = strtotime(date("Y-m-d"));
        $count['handle_order'] = $this->server->getOrderCount();//待处理订单
        $count['new_order'] = $this->server->addOrder($today);//今天新增订单
        $count['goods'] =  $this->server->productCount();//商品总数
        $count['article'] =  $this->server->articleCount();//文章总数
        $count['users'] = $this->server->userCount();//会员总数
        $count['today_login'] = $this->server->todayLogin($today);//今日访问
        $count['new_users'] = $this->server->newUser($today);//新增会员
        $count['comment'] = $this->server->commentCount();//最新评论
        $this->assign('count',$count);
        return $this->fetch();
    }

    public function get_sys_info(){
        $sys_info['os']             = PHP_OS;
        $sys_info['zlib']           = function_exists('gzclose') ? 'YES' : 'NO';//zlib
        $sys_info['safe_mode']      = (boolean) ini_get('safe_mode') ? 'YES' : 'NO';//safe_mode = Off
        $sys_info['timezone']       = function_exists("date_default_timezone_get") ? date_default_timezone_get() : "no_timezone";
        $sys_info['curl']			= function_exists('curl_init') ? 'YES' : 'NO';
        $sys_info['web_server']     = $_SERVER['SERVER_SOFTWARE'];
        $sys_info['phpv']           = phpversion();
        $sys_info['ip'] 			= GetHostByName($_SERVER['SERVER_NAME']);
        $sys_info['fileupload']     = @ini_get('file_uploads') ? ini_get('upload_max_filesize') :'unknown';
        $sys_info['max_ex_time'] 	= @ini_get("max_execution_time").'s'; //脚本最大执行时间
        $sys_info['set_time_limit'] = function_exists("set_time_limit") ? true : false;
        $sys_info['domain'] 		= $_SERVER['HTTP_HOST'];
        $sys_info['memory_limit']   = ini_get('memory_limit');
        $sys_info['version']   	    = Config::get('version.version');
        $mysqlinfo = Db::query("SELECT VERSION() as version");
        $sys_info['mysql_version']  = $mysqlinfo[0]['version'];
        if(function_exists("gd_info")){
            $gd = gd_info();
            $sys_info['gdinfo'] 	= $gd['GD Version'];
        }else {
            $sys_info['gdinfo'] 	= "未知";
        }
        return $sys_info;
    }
}