<?php
namespace app\index\controller;

use app\admin\controller\Common;
use app\common\controller\RedisServer as Redis;

class Index extends Common
{
    private static $redis;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        self::$redis = Redis::getInstance(array('host' => '127.0.0.1', 'port' => 6379),array('timeout'=>120,'db_id'=>4));
    }

    public function index()
    {
        dump(self::$redis->getInfo());
        self::$redis->set('user','name');
        return $this->fetch();
    }
}
